### ISSUE TITLE
Why is residual ignored for first layer

### ISSUE THREAD

**Issue by js0nwu** [jw9730/setvae#4]
Hello, thank you for releasing the code for your SetVAE paper.

I had a question about this line: https://github.com/jw9730/setvae/blob/7fdf4c6633cc69015bcd688383679699debc24ab/models/networks.py#L205

For the first decoder block, why is the residual from the hidden state ignored?

Thanks

**Comment by jw9730** [comment]
Hi ArkaneCow,

Please check Eq. (11) and Eq. (12) in the [paper](https://arxiv.org/pdf/2103.15619.pdf). There is no conditional dependency from z^(0) to z^(1) because z^(1) is designed to be the most coarse invariant latent variable that dictates the modulation of equivariant latent variable z^(0).

**Comment by js0nwu** [comment]
Thanks for the quick response. That makes sense. I also notice now that figure 3b shows the same setup as the code.
